### ISSUE TITLE
Process for selecting geometry causes hangs

### ISSUE THREAD

**Issue by fire** [WonderMediaProductions/Maya2glTF#101]
Only the select by type geometry seems to work without hanging the exporter.

https://stackoverflow.com/questions/21490307/select-all-by-type-geometry-equivalent-python-script

Not sure how to fix this. What does the button in the exporter do?

An artist mentioned that select by layers is not reliable. Some meshes may not be in layers.

**Comment by Ziriax** [comment]
Yeah we have the convention at WonderMedia to put meshes into layers, but that shouldn't really leak into the exporter defaults... We never had a crash when selecting geometry though...

**Comment by fire** [comment]
A hang means the program never crashes. It's a slight difference, but important!

**Comment by Ziriax** [comment]
Lol, yep. Now if Maya doesn't hang at least once a day, something is terribly wrong ;-)

**Comment by Ziriax** [comment]
Does it still hang with the latest version in `develop`?

**Comment by fire** [comment]
I haven't encountered this in a while. Make a new issue if it still exists.
