### ISSUE TITLE
build error for mac

### ISSUE THREAD

**Issue by cheery-doggo** [WonderMediaProductions/Maya2glTF#119]
Mac OS version is 10.15 
gcc version is 9.2.0

I executed command `sudo ./macos_build_plugin.sh`. When I got a build error like this.

[ 46%] Building CXX object CMakeFiles/maya2glTF.dir/src/Arguments.cpp.o
In file included from /Users/a12917/Desktop/src/Maya2glTF/src/Arguments.cpp:6:
In file included from /Users/a12917/Desktop/src/Maya2glTF/src/filesystem.h:11:
/Users/a12917/Desktop/src/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:52:9: error: redefinition of 'path'
                class path {
                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/filesystem:739:24: note: previous definition is here
class _LIBCPP_TYPE_VIS path {
                       ^
...

/Users/a12917/Desktop/src/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:814:28: error: no member named 'absolute' in 'std::__1::__fs::filesystem::path'
                        hash_combine(seed, path.absolute);
                                           ~~~~ ^
/Users/a12917/Desktop/src/Maya2glTF/build/filesystem/src/filesystem/filesystem.hpp:816:32: error: no member named 'leafs' in 'std::__1::__fs::filesystem::path'
                        for (const string &s : path.leafs) {
                                               ~~~~ ^
13 errors generated.
make[2]: *** [CMakeFiles/maya2glTF.dir/src/Arguments.cpp.o] Error 1
make[1]: *** [CMakeFiles/maya2glTF.dir/all] Error 2
make: *** [all] Error 2

**Comment by itsnotcaturday** [comment]
I'm no expert in C++, but I had the same error when trying to build this plugin on macOS Catalina.  I believe you can fix it by changing the filesystem.h file to just:

#include < filesystem > 

<img width="692" alt="Screen Shot 2020-02-26 at 9 26 10 PM" src="https://user-images.githubusercontent.com/18121967/75414807-9f7d6280-58de-11ea-8f1d-325b211376e1.png">

This allows Xcode to just use C++ 17 filesystem and it builds just fine (again...using macOS Catalina...didn't try this on Mojave or below....)

<img width="1199" alt="Screen Shot 2020-02-26 at 9 32 01 PM" src="https://user-images.githubusercontent.com/18121967/75415100-70b3bc00-58df-11ea-80fa-cad502a7bc42.png">

**Comment by Ziriax** [comment]
Ah, it seems newer versions of Xcode now have standard filesystem support.

@cheery-doggo Thanks for posting!

@itsnotcaturday Thanks for helping!
