### ISSUE TITLE
Request for export with Flat Shading 

### ISSUE THREAD

**Issue by thickaris** [WonderMediaProductions/Maya2glTF#124]
I tried to export with surface shader in maya as it is the only flat shader available but the textures didnt get exported with that material. Is it possible to convert the lambert shader automatically into Flat shader when exporting as gltf?

**Comment by thickaris** [comment]
![meshbasic](https://user-images.githubusercontent.com/29653448/83379100-57e40680-a3f8-11ea-9c9e-c0a90fda95a3.PNG)

i need it to get exported as this material meshbasicmaterial. instead it gets exported as meshstandardmaterial as i checked by importing into threejs. Please let me know how to export as meshbasic material from maya as it a flat shader

**Comment by Ziriax** [comment]
I'm not sure I follow you. Maya doesn't really have a "flat shader" as far as I know.

You just [set the vertex normals to be the face normals](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2018/ENU/Maya-Modeling/files/GUID-F3049631-81CD-4CE5-BC8C-26B9A5EE0006-htm.html)

Then you assign a Lambert or our PBR shader, apply textures, and export to GLTF (I have several flat shaded simple models in this repository).

Regarding ThreeJS, I don't know what rules it applies to convert the GLTF material to its internal shaders, maybe others could help here?

**Comment by thickaris** [comment]
@Ziriax I mean when exported as gltf from maya instead of using meshstandardshader is it possible to force meshbasicshader as this is the flat shader in threejs.

**Comment by thickaris** [comment]
> I'm not sure I follow you. Maya doesn't really have a "flat shader" as far as I know.
> 
> You just [set the vertex normals to be the face normals](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2018/ENU/Maya-Modeling/files/GUID-F3049631-81CD-4CE5-BC8C-26B9A5EE0006-htm.html)
> 
> Then you assign a Lambert or our PBR shader, apply textures, and export to GLTF (I have several flat shaded simple models in this repository).
> 
> Regarding ThreeJS, I don't know what rules it applies to convert the GLTF material to its internal shaders, maybe others could help here?

Thank you, how to convert vertex normal to face normal?

**Comment by Ziriax** [comment]
This tutorial might help, but Google "Maya set to face normals" will help too.

https://www.youtube.com/watch?v=0xB7nb0E448&t=11m
