### ISSUE TITLE
Updated support for Maya 2019

### ISSUE THREAD

**Issue by masterworm2** [WonderMediaProductions/Maya2glTF#126]
Hi there. Could you guys compile the plugin for 2019 please? I used the 2019 version from a issue request half a year ago but I can't export the to GLTF lower than 0.1 scale.

Thank you in advance.

**Comment by Ziriax** [comment]
Sure! I'm working on that, will bump the priority.

**Comment by Ziriax** [comment]
Just to make sure, you do mean the version for Windows 10 x64?

**Comment by Ziriax** [comment]
Could you test the version attached? If it works for you, I'll put on the releases page.

[maya2gltf_v1.0.1-rc2_b673d7bb3722_maya_2019.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/4779087/maya2gltf_v1.0.1-rc2_b673d7bb3722_maya_2019.zip)

**Comment by masterworm2** [comment]
> 
> 
> Sure! I'm working on that, will bump the priority.

Thank you for your quick response!

> 
> 
> Just to make sure, you do mean the version for Windows 10 x64?

Yep!

> 
> 
> Could you test the version attached? If it works for you, I'll put on the releases page.
> 
> [maya2gltf_v1.0.1-rc2_b673d7bb3722_maya_2019.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/4779087/maya2gltf_v1.0.1-rc2_b673d7bb3722_maya_2019.zip)

Works perfectly, thank you so much!
