### ISSUE TITLE
ambient color is not applied

### ISSUE THREAD

**Issue by Ma-Kn** [WonderMediaProductions/Maya2glTF#38]
My model is not displayed in the viewer below.
https://gltf-viewer.donmccurdy.com/

Because ambient color is not applied?
How can I solve it?

![image](https://user-images.githubusercontent.com/2511656/42936606-7c91a5e0-8b87-11e8-906d-1bb2762b1aa7.png)

![image](https://user-images.githubusercontent.com/2511656/42936710-cc019f18-8b87-11e8-995c-9edd4fc3c24b.png)

**Comment by Ziriax** [comment]
Currently we only convert the diffuse and transparency channels from non-PBR materials. 

PBR materials even don't have the concept of ambient, so I cannot convert it.

I
