### ISSUE TITLE
Ability to export materials with names

### ISSUE THREAD

**Issue by TyLindberg** [WonderMediaProductions/Maya2glTF#39]
Currently materials are exported without their names; however, it can be useful to reference materials by names in other renderers. How possible would it be to add this functionality to Maya2glTF?

**Comment by TyLindberg** [comment]
Awesome, thanks!

**Comment by Ziriax** [comment]
This should be fixed by [V0.9.8-alpha](../releases/tag/V0.9.8-alpha) (224bdcad245f1f1fde674e5fc1f24235901fff13)
