### ISSUE TITLE
backface visibility 

### ISSUE THREAD

**Issue by artistneel** [WonderMediaProductions/Maya2glTF#41]
I didnt find any option to make the backface visible in maya gltf shader, can you help

**Comment by Ziriax** [comment]
It is not yet part of the shader, see #34 why.

Basically backface culling is defined on a mesh in Maya, but on a shader in GLTF. Furthermore the Maya default value is to not cull backfaces, certainly not the right default value for GLTF.

That being said, I plan to release a new version this week that at least contains a dummy checkbox in the shader to set this.

Closing this as a duplicate of #34
