### ISSUE TITLE
alpha texture 

### ISSUE THREAD

**Issue by artistneel** [WonderMediaProductions/Maya2glTF#44]
Is there any way to add maps as alpha.

**Comment by Ziriax** [comment]
Currently the alpha channel is stored in the basecolor texture. You should also set the technique to transparent.

If a separate transparency texture is really desired, it could easily be implemented, but glTF requires the alpha to be part of the baseColor texture, so I would have to combine color and transparency channels in the exporter as a JPG or PNG.

Currently you have to manually create this RGB+alpha baseColor texture, eg using Photoshop, Gimp, Paint.net, etc...
