### ISSUE TITLE
Adding support for Maya 2014

### ISSUE THREAD

**Issue by haysclark** [WonderMediaProductions/Maya2glTF#47]
It would be awesome if older versions of Maya, like Maya 2014 could be supported.  The main reason is that Maya 2014 was one of the last version of Maya before AutoDesk switched to a subscription model.

**Comment by haysclark** [comment]
I know OSX support is a bit bleeding edge, re #24; however, after replacing "2018" with "2014" in _FindMaya.cmake_ the plug-in does start to compile.  Unfortunately, I hit a pretty obvious issue that 'maya/MUuid.h' does not exist in the Maya2014 includes.

```
Scanning dependencies of target maya2glTF
[ 46%] Building CXX object CMakeFiles/maya2glTF.dir/src/Arguments.cpp.o
In file included from /Users/hays/infinitedescent/Maya2glTF/src/Arguments.cpp:1:
/Users/hays/infinitedescent/Maya2glTF/src/externals.h:96:10: fatal error:
      'maya/MUuid.h' file not found
#include <maya/MUuid.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/maya2glTF.dir/src/Arguments.cpp.o] Error 1
make[1]: *** [CMakeFiles/maya2glTF.dir/all] Error 2
make: *** [all] Error 2
```

I'm just starting to dig into the code, and likely am over my head, but I wanted to pose the question and see if anyone thinks this endeavor is possible.  Others have mentioned possibly trying to implement a strategy-patterns to help fork behavior within the plug-in for various Maya versions. Any thoughts?

**Comment by Ziriax** [comment]
Thanks for trying this out! Unfortunately supporting 2014 is not a priority for us. Nevertheless let me try to help you out in my spare time :-)

The first problem: where do I download Maya 2014? 

IMO the best approach is to drop some features first, and see if the plugin runs at all.

So I would comment out the M3DView.h include in externals, and see where this code is used. Most likely only to refresh the viewport while exporting, not a high priority. AGL is deprecated and replaced by OpenGL and Maya 2014 relies on that (4a1fbefe00db0184aa088eaacdd08a023c666f9f)

The right handed tangent support can be commented out first.

Furthermore I use C++17 and Clang, that didn't exist in 2014, so you will most likely have to use GCC, but that raises a ton of other issues. Then the runtime libraries used might will not be compatible with Maya 2014... All in all this is going to be a major undertaking

But, you can try of course :-)

**Comment by haysclark** [comment]
@Ziriax Thanks for sparing some time.  I download Maya2014 from [](https://manage.autodesk.com/cep/); however, maybe it's only available to people with perpetual licenses.  I sent you an invite on LinkedIn so that I can forward you a link.

If it doesn't seem realistic, then maybe it would be best for me to figure out a Maya -> Colada -> GTFL, or an Automation setup, like Maya 2014 -> Maya 2018 -> GTFL.

**Comment by Ziriax** [comment]
Did you try https://github.com/KhronosGroup/COLLADA2GLTF?
