### ISSUE TITLE
Export clips with flag also exports a clip with entire animation

### ISSUE THREAD

**Issue by mikebourbeauart** [WonderMediaProductions/Maya2glTF#58]
I'd like to export clips using the plugin flags for the time slider/range. I'm able to do this using something like this in the extra flags lineedit:

`-acn "initPose" -ast 0 -aet 1 -acn "idleLoop" -ast 1 -aet 121 -acn "singIntro" -ast 121 -aet 166 -acn "singLoop" -ast 166 -aet 221 -acn "singEnd" -ast 221 -aet 268 -acn "newsIntro" -ast 268 -aet 313 -acn "newsLoop" -ast 313 -aet 363 -acn "newsOutro" -ast 363 -aet 421`

However this also exports a clip of the entire animation (which I don't want). 
![image](https://user-images.githubusercontent.com/10410125/45734320-24c0fb80-bbb2-11e8-83b0-0ac745833aa2.png)

Is there a way to export just my flagged clips and not generate a clip for the entire animation?

**Comment by Ziriax** [comment]
Are you using the Maya2glTF_UI combined with these flags? If so, can you try to set the export animation drop-down to "none", and try again? If you set it to time slider, it will add an extra clip for it. 

You could also use the plugin directly without UI, that should also work. When using the UI first, it should print the flags that were used.

If you use Trax, you can just disable a clip that you don't want to export (should work, but not yet tested).

You are the first user that is digging deeper, so you might find other weird things, thanks for the feedback 

We are not yet using this plug-in at WonderMedia in production, since we are still completing our own render engine, but as soon as we do, it should become more stable and get more features.

**Comment by mikebourbeauart** [comment]
> Are you using the Maya2glTF_UI combined with these flags? If so, can you try to set the export animation drop-down to "none", and try again? If you set it to time slider, it will add an extra clip for it.

I tried that and it failed. I hadn't thought about using it without the UI thought, that will probably solve the issue.

**Comment by mikebourbeauart** [comment]
update:

When I run within mel:
`loadPlugin "maya2glTF";

maya2glTF -sn "scene" -of "D:/Git_Stuff/rbg-test/assets/animations/gltf/rbg_test/"  -afr 24 -sf 1 -cpr "(C)2018 borbs" -ivt 0  -acn "idleLoop" -ast 1 -aet 121 -acn "singIntro" -ast 121 -aet 166 -acn "singLoop" -ast 166 -aet 221 -acn "singEnd" -ast 221 -aet 268 -acn "newsIntro" -ast 268 -aet 313 -acn "newsLoop" -ast 313 -aet 363 -acn "newsOutro" -ast 363 -aet 421 `

I'm getting this output:

`loadPlugin "maya2glTF";

maya2glTF -sn "scene" -of "D:/Git_Stuff/rbg-test/assets/animations/gltf/rbg_test/"  -afr 24 -sf 1 -cpr "(C)2018 borbs" -ivt 0  -acn "idleLoop" -ast 1 -aet 121 -acn "singIntro" -ast 121 -aet 166 -acn "singLoop" -ast 166 -aet 221 -acn "singEnd" -ast 221 -aet 268 -acn "newsIntro" -ast 268 -aet 313 -acn "newsLoop" -ast 313 -aet 363 -acn "newsOutro" -ast 363 -aet 421;
// Warning: line 1: Plug-in, "maya2glTF.mll", is already loaded.  Skipped. //
// Error: line 1: Cannot find procedure "maya2glTF_exportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_exportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_exportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI". //
// Error: line 1: Cannot find procedure "maya2glTF_advanceExportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_advanceExportProgressUI (command window: line 1).
maya2glTF (command window: line 3).
 //`

**Comment by mikebourbeauart** [comment]
Also just copy and pasting the output from maya2glTF_UI export doesn't work.

So running:
```
maya2glTF -sn "scene" -of "D:/GitStuff/rbg-test/assets/animations/gltf/rbg_lambert/" -sf 1 -cpr "(C)2018 borbs" -ivt 0  -acn "idleLoop" -ast 1 -aet 121 -acn "singIntro" -ast 121 -aet 166 -acn "singLoop" -ast 166 -aet 221 -acn "singEnd" -ast 221 -aet 268 -acn "newsIntro" -ast 268 -aet 313 -acn "newsLoop" -ast 313 -aet 363 -acn "newsOutro" -ast 363 -aet 421 -afr 24;
```


I get:

```
// Error: line 1: Cannot find procedure "maya2glTF". //
// Error: line 1: Cannot find procedure "maya2glTF".
Start of trace: (command window: line 1).
maya2glTF (command window: line 1).
 //
```

**Comment by Ziriax** [comment]
Good catch, the `maya2glTF_exportProgressUI` procedure is only available when you at least run the UI once. 

Also, the plugin is only loaded on demand (to allow upgrading it while running Maya)

Nobody has been using the plugin directly for a while...

I shouldn't give advice before trying myself, but with my busy schedule, if I would only answer when I'm 100% sure, that would mean long delayed replies 😉 

I'm going to log issues about the stuff you uncovered 👍 

To get you going, select the objects you want to export, and run the following in the Maya script editor:

```C
global string $gMainProgressBar;

global proc maya2glTF_exportProgressUI(int $max) {
  // This is defined on maya startup
 global string $gMainProgressBar;  

  $max = max(1, $max);

   progressBar -edit
  	-beginProgress
	-isInterruptable true
	-status "maya2glTF: exporting..."
	-minValue 0
	-maxValue $max
	$gMainProgressBar;
}

// Returns -1 if abortion is requested
global proc int maya2glTF_advanceExportProgressUI(string $stepName) 
{
    global string $gMainProgressBar;  // This is defined on maya startup

    progressBar -edit -step 1 -status ("maya2glTF: " + $stepName + "...") $gMainProgressBar;

    if(`progressBar -query -isCancelled $gMainProgressBar`) {
        print ("maya2glTF: aborting at "+`date -time`+"\n");
        return -1;
    }

    return 0;
}

loadPlugin "maya2glTF";

maya2glTF -sn "scene" -of "D:/Git_Stuff/rbg-test/assets/animations/gltf/rbg_test/" -afr 24 -sf 1 -cpr "(C)2018 borbs" -ivt 0 -acn "idleLoop" -ast 1 -aet 121 -acn "singIntro" -ast 121 -aet 166 -acn "singLoop" -ast 166 -aet 221 -acn "singEnd" -ast 221 -aet 268 -acn "newsIntro" -ast 268 -aet 313 -acn "newsLoop" -ast 313 -aet 363 -acn "newsOutro" -ast 363 -aet 421;

progressBar -edit -endProgress $gMainProgressBar;

unloadPlugin "maya2glTF";
```

Does that work for you?

**Comment by mikebourbeauart** [comment]
Worked great, thank you!

**Comment by Ziriax** [comment]
Thanks for reporting! Closing since I logged issues related to this
