### ISSUE TITLE
error occurs when compiling with mac ox

### ISSUE THREAD

**Issue by SXCC** [WonderMediaProductions/Maya2glTF#61]
after running macos_build_plugin.sh , error occurs and error message like this:

CMake Error at /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Maya (missing: MAYA_INCLUDE_DIR MAYA_LIBRARIES)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  modules/FindMaya.cmake:63 (find_package_handle_standard_args)
  CMakeLists.txt:10 (find_package)

**Comment by Ziriax** [comment]
What version of Maya do you have installed?

Before running cmake, try setting it explicitly, like `export MAYA_VERSION=2017`

I have only tested this on Maya 2018 for now.

**Comment by SXCC** [comment]
The version is 2017. 
Should I install maya devkit first? I'm not very familiar with maya plugin development. Thank you for answering my question.

**Comment by Ziriax** [comment]
Let me try for you first. I'll get back to you.

**Comment by Ziriax** [comment]
Fixed by 8f0ff1f9619eebd59d357f9bdf60688fe79e50e8
