### ISSUE TITLE
Plugin Commands with Mel

### ISSUE THREAD

**Issue by Harrolee** [WonderMediaProductions/Maya2glTF#68]
Hi! Thank you for the great plugin.

I want to use your plugin to export models in batches. I tried exporting models with mel using:
`maya2glTF -outputFolder "C:\Users\Lee\Desktop\export"`

I got the same error as mikebourbeauart in[ Issue 58](https://github.com/WonderMediaProductions/Maya2glTF/issues/58).

I tried running a version of the solution you posted with my script where his was:

```
global string $gMainProgressBar;


// Returns -1 if abortion is requested
global proc int maya2glTF_advanceExportProgressUI(string $stepName) 
{
    global string $gMainProgressBar;  // This is defined on maya startup

    progressBar -edit -step 1 -status ("maya2glTF: " + $stepName + "...") $gMainProgressBar;

    if(`progressBar -query -isCancelled $gMainProgressBar`) {
        print ("maya2glTF: aborting at "+`date -time`+"\n");
        return -1;
    }

    return 0;
}


maya2glTF -outputFolder "C:\Users\Lee\Desktop\export" -sn "cubeTest"
```

I got the error:

`Cannot find procedure "maya2glTF_exportProgressUI".
Start of trace: (command window: line 1).
maya2glTF_exportProgressUI (command window: line 1).
maya2glTF (command window: line 20).
`

How can I use plugin commands through mel or python?

Thank you again for your awesome work!

**Comment by Ziriax** [comment]
Yeah I should add a flag to disable progress UI when batch exporting... Or actually the other way around. Should be easy to do, I will do that asap.

But you need to define two procedures: 

```
global proc maya2glTF_exportProgressUI(int $max) {
    // This is defined on maya startup
    global string $gMainProgressBar;  

    $max = max(1, $max);

    progressBar -edit
        -beginProgress
        -isInterruptable true
        -status "maya2glTF: exporting..."
        -minValue 0
        -maxValue $max
        $gMainProgressBar;
}

// Returns -1 if abortion is requested
global proc int maya2glTF_advanceExportProgressUI(string $stepName) 
{
    global string $gMainProgressBar;  // This is defined on maya startup

    progressBar -edit -step 1 -status ("maya2glTF: " + $stepName + "...") $gMainProgressBar;

    if(`progressBar -query -isCancelled $gMainProgressBar`) {
        print ("maya2glTF: aborting at "+`date -time`+"\n");
        return -1;
    }

    return 0;
}
```

Note that these could be just empty procedures too, they just have to be defined.

**Comment by Harrolee** [comment]
Thank you for the quick response and for the code!

Followup question:

I received this error when I used it and ran maya2glTF -of with an existing directory:
`// Error: line 1: create_directories(p): invalid argument: operation not permitted // `

Do I need to to build the plugin from the repo in order to access additional functionality? 
I downloaded version 9.09 and loaded it in maya through the plugin folder.

**Comment by Ziriax** [comment]
That is interesting.

If you are on windows, make sure to pass the directory using / not \, so forward slashes, not backslashes.

Could you paste your complete command?

**Comment by Harrolee** [comment]
It worked! I am on windows and I was using back slashes when I should have been using forward slashes!
Thank you for your help!

**Comment by Ziriax** [comment]
Yeah it is sad that Windows uses backslashes for directory separation :-( 

Good luck and thanks for trying out Maya2glTF!
