### ISSUE TITLE
Maya2glTF Installation Issue on Mac OSX

### ISSUE THREAD

**Issue by shopHool** [WonderMediaProductions/Maya2glTF#69]
Hi, 
I'm having trouble installing Maya2glTF for Maya 2018 on my Mac? I stepped through the instructions via Terminal but It's not able to find the plugin? 

**Here's the error msg:**
Terence-iMac:Maya2glTF Terry$ sudo ./macos_build_plugin.sh
sudo: ./macos_build_plugin.sh: command not found

Would so love to get this working! Really would appreciate your help! 

Very best,
Terence

**Here's all the steps I did in Terminal:**
Terence-iMac:~ Terry$ git clone -b cmake https://github.com/WonderMediaProductions/Maya2glTF ~/Documents/Maya2glTF
Cloning into '/Users/Terry/Documents/Maya2glTF'...
remote: Enumerating objects: 537, done.
remote: Counting objects: 100% (537/537), done.
remote: Compressing objects: 100% (334/334), done.
remote: Total 3223 (delta 341), reused 367 (delta 198), pack-reused 2686
Receiving objects: 100% (3223/3223), 57.47 MiB | 4.18 MiB/s, done.
Resolving deltas: 100% (2345/2345), done.
git-lfs filter-process: git-lfs: command not found
fatal: The remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Terence-iMac:~ Terry$ cd ~/Documents/Maya2glTF
Terence-iMac:Maya2glTF Terry$ ./macos_build_plugin.sh
-bash: ./macos_build_plugin.sh: No such file or directory
Terence-iMac:Maya2glTF Terry$ sudo ./macos_build_plugin.sh
Password:
Sorry, try again.
Password:
sudo: ./macos_build_plugin.sh: command not found
Terence-iMac:Maya2glTF Terry$ sudo ./macos_delete_plugin.sh
sudo: ./macos_delete_plugin.sh: command not found
Terence-iMac:Maya2glTF Terry$ sudo ./macos_build_plugin.sh
sudo: ./macos_build_plugin.sh: command not found
Terence-iMac:Maya2glTF Terry$

**Comment by Ziriax** [comment]
From the log it seems you haven't enabled GIT LFS, please try installing and enabling this first, and then try again:

https://help.github.com/en/articles/configuring-git-large-file-storage

**Comment by shopHool** [comment]
Hi Ziriax,

I've installed Git LFS but don't know how to enable it. So the issue is that I'm not getting all the files: particulary this one, right? 

sudo ./macos_build_plugin.sh

Here's what I see in my terminal?
Terence-iMac:Maya2glTF Terry$ cd ~/Documents/Maya2glTF
Terence-iMac:Maya2glTF Terry$  sudo ./macos_build_plugin.sh
Password:
sudo: ./macos_build_plugin.sh: command not found

It's quite difficult to get all this installed on a mac, is there an easier way?

Very best,
Terence

**Comment by Ziriax** [comment]
Yes, the Mac plugin is not very artist friendly ;-) That's because we are Windows developers, and we really don't know much about Mac. 

I could try to build a version for you, but I'm not sure it will run on your Mac. What version of MacOS and Maya are you using?

But in your case, it just seems the source files were not downloaded correctly.

Could you:
1. delete the Maya2glTF folder completely
2. follow the installation instructions again, cloning etc (now that LFS is installed on your machine)

If that doesn't work, I will try to build the plugin for you, and we'll put it in the releases section if it works for you

**Comment by shopHool** [comment]
Hi Peter, 

Ok, I've tried again and it still isn't bringing down the **macos_build_plugin.sh** file.
Would it be because I cannot update Xcode to the latest version on my MacOS as I'm on Sierra V10.12.6? Also, I've installed CMAKE, but is there something I need to do with this? 
Also having installed Git LFS, what else would I need to do with this, should I enable it? Not sure how to do that.

Yes, it would be amazing if you could make your Mac plugin artist friendly! I would love to have it working on my Mac and I'm sure lots more people would appreciate it too! If you have time that is! 

Here's my specs?
** MacOS Version**
MacOS Sierra 
V10.12.6

** Maya Version**
Maya 2018 or 2019

Very best,
Terence

**Comment by Ziriax** [comment]
Okay, I will build the Mac version this weekend then.

Out of curiosity, could you list the content of the directory that was cloned (using the `ls` command or a screenshot using Finder)?

**Comment by shopHool** [comment]
Excellent, really appreciate that! 

Yeah, here's all the files I get using the GIT LFS. I may have not enabled the GIT LFS though.. 
![Screen Shot 2019-03-15 at 9 23 29 AM](https://user-images.githubusercontent.com/37537349/54420236-5ea63100-4701-11e9-8598-f205ae693423.png)

**Comment by Ziriax** [comment]
This weekend was a bit hectic, I'll keep you posted when the MacOS binary is ready for testing.

**Comment by Ziriax** [comment]
@shopHool Please find attached a ZIP of a potential MacOS release.

You should unzip this to `/Users/Shared` (in Finder, you need to [enable your library folder](http://osxdaily.com/2013/10/28/show-user-library-folder-os-x-mavericks/) to find it)


After this your folder structure should contain the following files:

```
/Users/Shared/Autodesk/maya/maya2glTF/PBR/images/damaged_helmet_specular_env.dds
/Users/Shared/Autodesk/maya/maya2glTF/PBR/images/damaged_helmet_diffuse_env.dds
/Users/Shared/Autodesk/maya/maya2glTF/PBR/images/brdfLUT.png
/Users/Shared/Autodesk/maya/maya2glTF/PBR/shaders/glTF_PBR.ogsfx
/Users/Shared/Autodesk/maya/2018/plug-ins/maya2glTF.bundle
/Users/Shared/Autodesk/maya/scripts/maya2glTF_assignPbrShader.mel
/Users/Shared/Autodesk/maya/scripts/maya2glTF_exportAllScenes.mel
/Users/Shared/Autodesk/maya/scripts/maya2glTF_version.mel
/Users/Shared/Autodesk/maya/scripts/maya2glTF_UI.mel
```

Then restart Maya, and type `maya2glTF_UI`in the script window.

Please let me know if this worked for you.

Thanks,
Peter

[Autodesk.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/2992510/Autodesk.zip)

**Comment by shopHool** [comment]
Hi Peter, you are my hero! YES, it works fantastic! Gltf with PBT and animation comes into code nicely!
Thanks so much making this work for Mac! 

Very best,
Terence

**Comment by Ziriax** [comment]
That is good news! 

I will make this release available then in the downloads section. 

Thanks for helping out!

**Comment by shopHool** [comment]
No problem! Thanks again!
