### ISSUE TITLE
Which tool do you used for generating the DDS image?

### ISSUE THREAD

**Issue by xu-xionglong** [WonderMediaProductions/Maya2glTF#72]
When I try to import my own DDS image generated from [cmft](https://github.com/dariomanesku/cmft), Maya crashed immediately. It seems that Maya does not support all formats of DDS. Would you please tell me that which DDS generation tool you are using?

**Comment by Ziriax** [comment]
What version of Maya are you using?

**Comment by xu-xionglong** [comment]
> What version of Maya are you using?

I use Maya 2018 in macOS

**Comment by Ziriax** [comment]
Ah that version contains a bug in its DDS loader.

What worked for me, was to use texconv to load and save the DDS

**Comment by xu-xionglong** [comment]
Thanks. I will try

**Comment by Ziriax** [comment]
Did that work for you?

**Comment by xu-xionglong** [comment]
No. The image become all white if I convert it from 32bit float to 32bit uint or 8bit uint. Even I keep the format as 32bit float, the hue is changed.
