### ISSUE TITLE
Translate Arnold Standard Surface into GLTF properties

### ISSUE THREAD

**Issue by fire** [WonderMediaProductions/Maya2glTF#74]
It should be possible to translate Arnold Standard materials into GLTF PBR materials, since they both use the same PBR theory, texture paths and constants.

**Comment by Ziriax** [comment]
Interesting. I don't know anything about Arnold, but could investigate. 

That being said, the code should be very easy to implement if it indeed matches that closely to PBR, so a pull request is welcome :-)

**Comment by fire** [comment]
Ah, I haven't written a Maya plugin before, but you make it sound easy.

**Comment by fire** [comment]
Here's a Maya 2018 screenshot of the Arnold Standard material.

![Screen Shot 2019-05-23 at 11 08 40 AM](https://user-images.githubusercontent.com/32321/58276088-69a5bf00-7d4b-11e9-8adf-2d1b0464b810.png)

**Comment by Ziriax** [comment]
If you have a bit of experience with C/C++, then it should be easy.

Look at the file https://github.com/WonderMediaProductions/Maya2glTF/blob/master/src/ExportableMaterial.cpp

If that looks familiar, it should be fairly easy I guess. 

Otherwise I will take a look at it, if you can provide me with a test scene :-)

**Comment by fire** [comment]
Try this model.

https://share.substance3d.com/libraries/3136

https://drive.google.com/file/d/1jyqHwW56O6UTcQnWboGUrtpJTNWmbIFa/view?usp=sharing

**Comment by fire** [comment]
Screenshot of the grenade.

![Screen Shot 2019-05-23 at 11 49 38 AM](https://user-images.githubusercontent.com/32321/58278432-dcfdff80-7d50-11e9-82e9-141a9306678a.png)

**Comment by fire** [comment]
By the way, the heightmap is hidden within the bump map where the normals are.

**Comment by Ziriax** [comment]
Thanks! I'm sorry but we are currently code-rushing for a deadline, so I'll get back to this ASAP

**Comment by fire** [comment]
Ping!

**Comment by Ziriax** [comment]
Sorry, still very busy with other projects :(

Please bare in mind this is an open source project, so pull requests to implement this are welcome!

**Comment by fire** [comment]
Started looking into this. https://github.com/fire/Maya2glTF/tree/aiStandardMaterial

Not ready yet, but it's in progress.

**Comment by fire** [comment]
The first draft is in. Will file new reports on the new bugs.
