### ISSUE TITLE
Skinning error with single hierachy character

### ISSUE THREAD

**Issue by westomopresto** [WonderMediaProductions/Maya2glTF#75]
![2019-07-23_14-07-28](https://user-images.githubusercontent.com/21068952/61747701-48fde380-ad53-11e9-8f33-ba60e2421786.gif)

Inside maya

![2019-07-23_14-08-34](https://user-images.githubusercontent.com/21068952/61747746-616dfe00-ad53-11e9-92e5-127eeb32c3cb.gif)

result inside Windows 3D Viewer

![2019-07-23_14-09-08](https://user-images.githubusercontent.com/21068952/61747771-734fa100-ad53-11e9-907b-d4c62ff413b3.gif)

result inside Google Poly

export results & maya scene

[GLTF_result.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/3424085/GLTF_result.zip)
[stoker_walk_cycle.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/3424087/stoker_walk_cycle.zip)

Using Maya 2018

**Comment by Ziriax** [comment]
Please note that the Windows GLTF viewers don't work very well when it comes to animation...

These GLTF viewers handle GLTF animation better (but all of these have limitations when it comes to the maximum number of joints and morph-targets that are supported)

* https://github.com/AnalyticalGraphicsInc/gltf-vscode
* https://gltf-viewer.donmccurdy.com/

**But indeed your scene doesn't export correctly with the master version, but seems to export fine with the latest version of Maya2glTF, that is not published yet. I'll attach it for you, please test this to see if it works for you** 
[Maya2glTF_V1.0.0.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/3427334/Maya2glTF_V1.0.0.zip)
[gltf-export.zip](https://github.com/WonderMediaProductions/Maya2glTF/files/3427335/gltf-export.zip)

**Comment by westomopresto** [comment]
Thanks very much!
Yeah it exports much better than before.
I'm having an issue with materials, but I think it's related to this model only.
(That green/black checker material for the legs)

The skinning issue is fixed with that 1.0 version you attached. Thanks <3
