### ISSUE TITLE
Full paths for textures cause hang

### ISSUE THREAD

**Issue by fire** [WonderMediaProductions/Maya2glTF#85]
When loading textures with paths from another computer, the load hangs.

I'm not sure how to reproduce this without using the production models that I can't distribute.

**Comment by Ziriax** [comment]
At WonderMedia, we only use textures that are stored on another PC (a NAS), so something else must be going on.

Are you experiencing these crashes on Windows or Mac? And can you give me an example of such a file path, and if possible (on Windows), attach the Visual Studio debugger to Maya while doing an export, and then show me the stack trace when it crashes? On Mac something similar might be possible with Xcode, but I don't know how.
