### ISSUE TITLE
Root motion is not kept

### ISSUE THREAD

**Issue by fire** [WonderMediaProductions/Maya2glTF#86]
In games, we use motion on the root and call it root motion.

If only meshes are selected, we aren't able to keep the root motion and animations are lost.

Being able to export the whole scene with the root controller node should fix this.

Thanks

**Comment by Ziriax** [comment]
Does it work when you also select the root controller and then export and/or disable the `selected objects only` option?

Full scene export is certainly possible, but the exporter was designed as a mesh exporter, so will require a bit of refactoring.

**Comment by fire** [comment]
Used the workaround of "Select all geometry by type".
