### ISSUE TITLE
Scaling the scene adds a node rather than scaling each node

### ISSUE THREAD

**Issue by fire** [WonderMediaProductions/Maya2glTF#89]
Scaling the scene adds a node rather than reconstructing each node to be different.

Here is some example code, if there's a maya function to do it'll work too.

https://github.com/assimp/assimp/blob/master/code/PostProcessing/ScaleProcess.cpp#L136

**Comment by Ziriax** [comment]
There's a flag for that, `-bakeScalingFactor` or `-bsf`, but I haven't tested this very well. Baking the scale factors will currently change the vertex positions, it will not change the nodes at all.
