### ISSUE TITLE
Checkbox to disable SSC

### ISSUE THREAD

**Issue by fire** [WonderMediaProductions/Maya2glTF#90]
Segment Scale Compensate doubles the number of bones, can there be a checkbox to disable it?

https://knowledge.autodesk.com/support/maya/troubleshooting/caas/simplecontent/content/turning-segment-scale-compensate-maya-how-to-make-maya-rigs-play-nice-unity.html

**Comment by Ziriax** [comment]
Sure, that could be added easily. For now, just pass the `-isc` or `-ignoreSegmentScaleCompensation` extra flag. It seems I forgot to document this in the README...

**Comment by fire** [comment]
You can close this issue when the README is updated then.

**Comment by Ziriax** [comment]
Yes, but a checkbox is certainly needed!

I wanted to automate this, e.g. not adding extra nodes even if segment scale is enabled, also by looking at all animations, but this isn't compatible with our new asset export flow. That is, we have one rig scene per character that is exported as a non-animating glTF file, and each animation is a separate Maya file, also exported as a GLTF file, and then we use our [.NET Core GLTF merge tool](https://github.com/WonderMediaProductions/Maya2glTF/tree/develop/tools/ModelClipMerger) to combine everything into a single glTF file. The merge tool could then optimize this away, but I haven't implemented that yet.
